Repository Team-B1ND/dds-compose, pull requests merged in 2024-11, with the labels that each got.

#33 Release 1.0.10
  README.md
  app/src/main/java/com/b1nd/dodam/designsystem/MainActivity.kt
  dodam-design-system/build.gradle.kts
  dodam-design-system/src/commonMain/composeResources/drawable/ic_chart.xml
  dodam-design-system/src/commonMain/composeResources/drawable/ic_pen.xml
  dodam-design-system/src/commonMain/kotlin/com/b1nd/dodam/designsystem/component/Avatar.kt
  dodam-design-system/src/commonMain/kotlin/com/b1nd/dodam/designsystem/component/Indicator.kt
  dodam-design-system/src/commonMain/kotlin/com/b1nd/dodam/designsystem/foundation/DodamIcons.kt
Labels: bug, enhancement

#36 Fix:Handling Weight Size
  README.md
  dodam-design-system/build.gradle.kts
  dodam-design-system/src/commonMain/kotlin/com/b1nd/dodam/designsystem/component/Indicator.kt
Labels: bug

#38 Release 1.1.0
  README.md
  dodam-design-system/build.gradle.kts
  dodam-design-system/src/commonMain/kotlin/com/b1nd/dodam/designsystem/component/DodamEmpty.kt
Labels: enhancement

#40 Release 1.2.0
  README.md
  dodam-design-system/build.gradle.kts
  dodam-design-system/src/commonMain/kotlin/com/b1nd/dodam/designsystem/component/ModalBottomSheet.kt
Labels: enhancement
